x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1

properties:
  # Tester image for running verification tests
  tester.image:
    type: string
    default: $REGISTRY/wso2-apim/tester:$TAG
    x-google-marketplace:
      type: FULL
