x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "4.5.0"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release of WSO2 APIM Kubernetes deployment with support for
      API Manager Control Plane (ACP), API Platform for Kubernetes (APK),
      and APK Agent integration on Google Cloud Platform.
    releaseTypes:
      - Feature
    recommended: false

  clusterConstraints:
    resources:
      - replicas: 1
        requests:
          cpu: 500m
          memory: 1Gi
    k8sVersion: ">=1.24.0"

  images:
    deployer:
      properties:
        imageRegistry:
          type: REGISTRY
        imageRepo:
          type: REPO_WITHOUT_REGISTRY
        imageTag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
    title: Application name
    description: The name of the application instance

  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
    title: Namespace
    description: The Kubernetes namespace where the application will be deployed

required:
  - name
  - namespace
